id: P000661
initial_creation_type: ocr
source_metadata:
  id: bdr:W23953
  title: མཁས་གྲུབ་ཆེན་པོ་རྣམ་གྲོལ་བཟང་པོའི་རྣམ་ཐར་དད་པའི་སྤུ་ལོང་གཡོ་བྱེད་ངོ་མཚར་ཅན
  author: ''
  volumes:
    f89313fa1111499c8076149add49a310:
      image_group_id: I3547
      title: ''
      volume_number: 1
      total_pages: 106
      base_file: v001.txt
