id: I2AE6439B
legacy_id: P000661
ocr_import_info:
  bdrc_scan_id: W23953
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T17:55:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:21:54.869257+00:00'
last_modified: 2022-09-02 13:22:06.171648
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23953
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23953
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཁས་གྲུབ་ཆེན་པོ་རྣམ་གྲོལ་བཟང་པོའི་རྣམ་ཐར་དད་པའི་སྤུ་ལོང་གཡོ་བྱེད་ངོ་མཚར་ཅན།
  author: དམར་སྒོམ་བསོད་ནམས་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.7120593089223693
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I3547:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3547
      total_pages: 106
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3547.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7120593089223693
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
