id: I2AE6439B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:56:14+00:00'
last_modified: '2022-06-07T12:34:50.614426+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23953
  title: མཁས་གྲུབ་ཆེན་པོ་རྣམ་གྲོལ་བཟང་པོའི་རྣམ་ཐར་དད་པའི་སྤུ་ལོང་གཡོ་བྱེད་ངོ་མཚར་ཅན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3EFF:
      image_group_id: I3547
      title: ''
      total_pages: 106
      order: 1
      base_file: 3EFF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
